### ISSUE TITLE
relax the requirement on the first column name

### ISSUE THREAD

**Issue by RNAer** [biocore/emperor#345]
I met a problem as following:

```
$ make_emperor.py -i bray_curtis_pc.txt -m ../taxa_meta/taxa_meta_corrected.txt -o foo
Traceback (most recent call last):
  File "/home/zhxu5194/anaconda/envs/qiime_1.9/bin/make_emperor.py", line 643, in <module>
    main()
  File "/home/zhxu5194/anaconda/envs/qiime_1.9/bin/make_emperor.py", line 609, in main
    fp_out.write(format_mapping_file_to_js(mapping_data, header, header))
  File "/home/zhxu5194/anaconda/envs/qiime_1.9/lib/python2.7/site-packages/emperor/format.py", line 197, in format_mapping_file_to_js
    if category != 'SampleID' and map_object.isNumericCategory(category)]
  File "/home/zhxu5194/anaconda/envs/qiime_1.9/lib/python2.7/site-packages/emperor/qiime_backports/util.py", line 204, in isNumericCategory
    category_values = self.getCategoryValues(self.SampleIds, category)
  File "/home/zhxu5194/anaconda/envs/qiime_1.9/lib/python2.7/site-packages/emperor/qiime_backports/util.py", line 193, in getCategoryValues
    return [self._metadata[sid][category] for sid in sample_ids]
KeyError: 'taxon_oid'
```

It is ok once I changed my 1st column name from "taxon_oid" to "SampleID". IMHO, emperor should allow whatever column names for general use cases. It should be an easy fix.

**Comment by ElDeveloper** [comment]
I like this idea, though I'm not sure it will have some other
repercussions. At the very least we should improve the error message we
are getting in this case. Maybe even provide a --sample-id-column flag
where you can set what column you want to use as index?

**Comment by transcript** [comment]
For anyone who finds this through a web search, like I did, it seems that the words "Name", "Sample", and "ID" cannot be present in the first column of the metadata header.  Underscores cannot be used to separate the words (e.g. "Sample_ID" still fails), but the words can be concatenated together (e.g. "SampleID" is okay).

**Comment by ElDeveloper** [comment]
This is no longer an issue in the latest version of Emperor. So as long as identifiers are stored in the DataFrame's index it can be named whatever you want. If used through QIIME2, then QIIME2's rules apply 👍
