### ISSUE TITLE
setup.py broken (by use of set type for reqs?)

### ISSUE THREAD

**Issue by ikirker** [biocore/emperor#631]
Steps to reproduce:

  - Using Python 2.7.12 or 3.6.3:

```bash
virtualenv venv
source venv/bin/activate
pip install emperor
```

Output:
```
Collecting emperor
  Downloading emperor-0.9.60.tar.gz (4.1MB)
    100% |████████████████████████████████| 4.1MB 304kB/s 
    Complete output from command python setup.py egg_info:
    error in emperor setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Unordered types are not allowed
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-_Fn1vc/emperor/
```

As far as I can tell this appears to be because `install_requires` is of `set` type, which, as the error message says, is not allowed here. Changing it to a list should probably fix it? The add/remove code would presumably also need changing. (I'm guessing that the easy of add/remove is why someone used a set, but it seems weird that they presumably altered and then... didn't test it?)

**Comment by ikirker** [comment]
As a sort of additional note here: as far as I can tell the current tests do not use the setup.py installation, which is why the tests badge doesn't reflect that this is broken. It would probably be worth making the test scripts try an installation from pip.

**Comment by ElDeveloper** [comment]
@ikirker I was not able to reproduce this locally. Can you let me know what version of pip are you using, here's what I used:

```
$ pip --version
pip 9.0.1 from /Users/yoshikivazquezbaeza/miniconda/envs/issue-631/lib/python2.7/site-packages (python 2.7)
$ python --version
Python 2.7.12 :: Continuum Analytics, Inc.
```

`setup.py` is tested with when Travis runs. However, what you may have found is that the old version of `setup.py` has this problem i.e. the one from release 0.9.60, which we haven't tested in the CI system in a while.

**Comment by ikirker** [comment]
@ElDeveloper 

Seems the same problem occurs with a fresh copy of the new-api branch (the default one if I click the **Code** tab here) *and* the 0.9.60 release in PyPi.

```
/tmp/emperor-test$ python --version
Python 2.7.12
/tmp/emperor-test$ pip --version
pip 9.0.1 from /shared/ucl/apps/python/2.7.12/gnu-4.9.2/lib/python2.7/site-packages (python 2.7)
/tmp/emperor-test$ virtualenv --version
15.0.3
/tmp/emperor-test$ virtualenv venv
New python executable in /tmp/emperor-test/venv/bin/python2.7
Also creating executable in /tmp/emperor-test/venv/bin/python
Installing setuptools, pip, wheel...done.
/tmp/emperor-test$ source venv/bin/activate
(venv) /tmp/emperor-test$ python --version
Python 2.7.12
(venv) /tmp/emperor-test$ pip --version
pip 9.0.1 from /tmp/emperor-test/venv/lib/python2.7/site-packages (python 2.7)
(venv) /tmp/emperor-test$ wget -q https://github.com/biocore/emperor/archive/new-api.zip
(venv) /tmp/emperor-test$ pip install new-api.zip
Processing ./new-api.zip
    Complete output from command python setup.py egg_info:
    error in emperor setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Unordered types are not allowed

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-8S9TWF-build/
(venv) /tmp/emperor-test$ pip install emperor
Collecting emperor
  Using cached emperor-0.9.60.tar.gz
    Complete output from command python setup.py egg_info:
    error in emperor setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Unordered types are not allowed

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-kDoH_r/emperor/
(venv) /tmp/emperor-test$ pip install --no-cache-dir emperor
Collecting emperor
  Downloading emperor-0.9.60.tar.gz (4.1MB)
    100% |████████████████████████████████| 4.1MB 62.3MB/s
    Complete output from command python setup.py egg_info:
    error in emperor setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Unordered types are not allowed

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-Nh4Jqp/emperor/
(venv) /tmp/emperor-test$

```


On the other hand, it all works if I unpack the zip of the fresh download of the new-api branch, and change the sets into lists (and change the `|` to `+`):

```python
base = ["numpy >= 1.7", "scipy >= 0.17.0", "click", "pandas",
        skbio_2, "jinja2 >= 2.9", "future"]
doc = ["Sphinx < 1.6", "sphinx-bootstrap-theme"]
test = ["nose >= 0.10.1", "pep8", "flake8"]
all_deps = base + doc + test
```


And, a colleague pointed out to me that, as you said, it *does* use the `setup.py` in the tests, just with `pip install -e '.[all]`, so I tried that with a new copy of the new-api version as well:

```
# (Starting from scratch)
/tmp/emperor-test$ ls
/tmp/emperor-test$ virtualenv venv
New python executable in /tmp/emperor-test/venv/bin/python2.7
Also creating executable in /tmp/emperor-test/venv/bin/python
Installing setuptools, pip, wheel...sourcedone.
/tmp/emperor-test$ source venv/bin/activate
(venv) /tmp/emperor-test$ wget -q https://github.com/biocore/emperor/archive/new-api.zip
(venv) /tmp/emperor-test$ ls
new-api.zip  venv
(venv) /tmp/emperor-test$ unzip -q new-api.zip
(venv) /tmp/emperor-test$ cd emperor-new-api/
(venv) /tmp/emperor-test/emperor-new-api$ pip install -e '.[all]' --verbose
Obtaining file:///tmp/emperor-test/emperor-new-api
  Running setup.py (path:/tmp/emperor-test/emperor-new-api/setup.py) egg_info for package from file:///tmp/emperor-test/emperor-new-api
    Running command python setup.py egg_info
    error in emperor setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Unordered types are not allowed
Cleaning up...
Command "python setup.py egg_info" failed with error code 1 in /tmp/emperor-test/emperor-new-api/
Exception information:
Traceback (most recent call last):
  File "/tmp/emperor-test/venv/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/tmp/emperor-test/venv/lib/python2.7/site-packages/pip/commands/install.py", line 335, in run
    wb.build(autobuilding=True)
  File "/tmp/emperor-test/venv/lib/python2.7/site-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/tmp/emperor-test/venv/lib/python2.7/site-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/tmp/emperor-test/venv/lib/python2.7/site-packages/pip/req/req_set.py", line 518, in _prepare_file
    abstract_dist.prep_for_dist()
  File "/tmp/emperor-test/venv/lib/python2.7/site-packages/pip/req/req_set.py", line 129, in prep_for_dist
    self.req_to_install.run_egg_info()
  File "/tmp/emperor-test/venv/lib/python2.7/site-packages/pip/req/req_install.py", line 439, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/tmp/emperor-test/venv/lib/python2.7/site-packages/pip/utils/__init__.py", line 707, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command "python setup.py egg_info" failed with error code 1 in /tmp/emperor-test/emperor-new-api/
(venv) /tmp/emperor-test/emperor-new-api$
```

So, same error, just with the Exception stacktrace. Clearly this *did* work for your last tests, and I'm struggling a little to work out what the significant difference is at this point.

**Comment by ikirker** [comment]
I can now reproduce this in a completely clean Ubuntu 17.10 Vagrant box:

```
vagrant init ubuntu/artful64
vagrant up
vagrant ssh
sudo apt install -y build-essential libssl-dev libz-dev libreadline-dev libbz2-dev libncurses-dev libsqlite3-dev libdb-dev libgdbm-dev
wget https://www.python.org/ftp/python/2.7.14/Python-2.7.14.tar.xz
cd Python-2.7.14/
./configure --with-ensurepip
make
sudo make install
sudo pip install virtualenv
virtualenv venv
source venv/bin/activate
pip install emperor
```

Gives pages and pages of installation and setup output, and then:

```
(venv) vagrant@ubuntu-artful:~/Python-2.7.14$ pip install emperor
Collecting emperor
  Downloading emperor-0.9.60.tar.gz (4.1MB)
    100% |████████████████████████████████| 4.1MB 355kB/s 
    Complete output from command python setup.py egg_info:
    error in emperor setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Unordered types are not allowed
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-7B7O4u/emperor/
(venv) vagrant@ubuntu-artful:~/Python-2.7.14$ 
```

**Comment by ikirker** [comment]
I tried copying the miniconda steps used in the Travis tests, to see if I could get a successful installation there and work backwards to see what was breaking, and that worked.

So, it looks like the error I'm getting comes from `check_requirements` in `lib/python2.7/site-packages/setuptools/dist.py`.

Here's the version I get in the clean Ubuntu (Artful) box, where the setup fails:

```python
def check_requirements(dist, attr, value):
    """Verify that install_requires is a valid requirements list"""
    try:
        list(pkg_resources.parse_requirements(value))
        if isinstance(value, (dict, set)):
            raise TypeError("Unordered types are not allowed")
    except (TypeError, ValueError) as error:
        tmpl = (
            "{attr!r} must be a string or list of strings "
            "containing valid project/version requirement specifiers; {error}"
        )
        raise DistutilsSetupError(tmpl.format(attr=attr, error=error))
```


```python
>>> import setuptools
>>> print(setuptools.version.__version__)
38.2.4
```

And here's the miniconda version I get if I copy the installation steps in the emperor Travis tests, where setup succeeds:

```python
def check_requirements(dist, attr, value):
    """Verify that install_requires is a valid requirements list"""
    try:
        list(pkg_resources.parse_requirements(value))
    except (TypeError, ValueError) as error:
        tmpl = (
            "{attr!r} must be a string or list of strings "
            "containing valid project/version requirement specifiers; {error}"
        )
        raise DistutilsSetupError(tmpl.format(attr=attr, error=error))
```

```python
>>> import setuptools
>>> print(setuptools.version.__version__)
36.5.0.post20170921
```

So I guess, If I'm reading this right, the current Travis tests will fail if/when Conda updates their setuptools version to include the type check.

**Comment by ikirker** [comment]
And, yes, if I force-downgrade the version of setuptools I'm using, installation succeeds; conversely if I use pip to upgrade the version in the miniconda environment, installation fails.

**Comment by ElDeveloper** [comment]
@ikirker, thanks for looking into this. If the problem is future setuptools, then we better be prepared. I've now submitted a PR to convert the requirements into lists, see #637.

**Comment by ikirker** [comment]
@ElDeveloper Thank you for putting the fix in, and please accept my apologies for making some incorrect assumptions and getting a bit confused in the beginning.

**Comment by owainkenwayucl** [comment]
Hey, at the risk of poking on a broken ticket, for anyone who finds this and is trying to get qiime to work, qiime currently has version reqs: emperor<1.0.0,>=0.9.51 which of course means that it tries to install 0.9.60 which has this problem.

Luckily it doesn't seem to be a problem with 0.9.51.
