### ISSUE TITLE
After recent Qiita update, "Principal Coordinate Analysis Biplot [pcoa_biplot] (qiime2 2022.11.1)" now fails

### ISSUE THREAD

**Issue by ekunselman** [biocore/emperor#814]
Error executing Principal Coordinate Analysis Biplot [pcoa_biplot]: ['Traceback (most recent call last):\n', ' File "/home/qiita/miniconda3/envs/qiime2-2022.11/lib/python3.8/site-packages/qiita_client/plugin.py", line 265, in __call__\n success, artifacts_info, error_msg = task(\n', ' File "/home/qiita/miniconda3/envs/qiime2-2022.11/lib/python3.8/site-packages/qiita_client/plugin.py", line 105, in __call__\n return self.function(qclient, server_url, job_id, output_dir)\n', ' File "/home/qiita/qiita_spots/qp-qiime2/qp_qiime2/qp_qiime2.py", line 536, in call_qiime2\n atype = Q2_QIITA_SEMANTIC_TYPE[str(q2artifact.type)]\n', 'KeyError: "PCoAResults % Properties(\'biplot\')"\n']

Using 'Unweighted Unifrac PCoA results', and a collapsed, rarefied, 'relative frequency table'

**Comment by ElDeveloper** [comment]
@ekunselman, as best as I can tell from the traceback, this is a Qiita issue so I'll move that over there 👍

**Comment by ElDeveloper** [comment]
https://github.com/qiita-spots/qiita/issues/3266
